//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGiaVatTu
    {
        public string Ma_bao_gia_vat_tu { get; set; }
        public decimal Gia_goc { get; set; }
        public Nullable<int> Chiet_khau { get; set; }
        public decimal Gia_chiet_khau { get; set; }
        public string Ghi_chu { get; set; }
        public System.DateTime Thoi_gian { get; set; }
        public string Ma_vat_tu { get; set; }
        public string Ma_cua_hang { get; set; }
    
        public virtual CuaHangVatTu CuaHangVatTu { get; set; }
        public virtual DanhMucVatTu DanhMucVatTu { get; set; }
    }
}
