//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHangVatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuaHangVatTu()
        {
            this.BaoGiaVatTu = new HashSet<BaoGiaVatTu>();
            this.ThanhToanNganHang = new HashSet<ThanhToanNganHang>();
            this.ThanhToanTrucTiep = new HashSet<ThanhToanTrucTiep>();
        }
    
        public string Ma_cua_hang { get; set; }
        public string Ten_cua_hang { get; set; }
        public string Ghi_chu { get; set; }
        public System.DateTime Thoi_gian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoGiaVatTu> BaoGiaVatTu { get; set; }
        public virtual DiaChi DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToanNganHang> ThanhToanNganHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToanTrucTiep> ThanhToanTrucTiep { get; set; }
    }
}
