//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DanhMucVatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucVatTu()
        {
            this.BaoGiaVatTu = new HashSet<BaoGiaVatTu>();
        }
    
        public string Ma_vat_tu { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên vật tư")]
        public string Ten_vat_tu { get; set; }
        public string Quy_chuan { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn chủng loại")]
        public string Chung_loai { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn đơn vị tính")]
        public string Don_vi_tinh { get; set; }
        public string Ghi_chu { get; set; }
        public System.DateTime Thoi_gian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoGiaVatTu> BaoGiaVatTu { get; set; }
    }
}
