//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenVatLieu
    {
        public string Ma_nguyen_vat_lieu { get; set; }
        public string Ten { get; set; }
        public string Phan_loai { get; set; }
        public string Nha_san_xuat { get; set; }
        public int Ton_kho { get; set; }
        public decimal Gia_don_vi { get; set; }
        public decimal Gia_tri_tong { get; set; }
        public string Mo_ta { get; set; }
        public System.DateTime Thoi_gian { get; set; }
    }
}
