//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToanTrucTiep
    {
        public int Ma_thanh_toan { get; set; }
        public string Ten_nguoi_nhan { get; set; }
        public string Dia_chi { get; set; }
        public string So_dien_thoai { get; set; }
        public string Ma_cua_hang { get; set; }
    
        public virtual CuaHangVatTu CuaHangVatTu { get; set; }
    }
}
