//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAS_UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaoGiaVatTu
    {
        public System.Guid ID_Cua_hang { get; set; }
        public System.Guid ID_Vat_tu { get; set; }
        public System.Guid ID_Bao_gia { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mã báo giá")]
        public string Ma_bao_gia { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá gốc")]
        public decimal Gia_goc { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập chiết khấu")]
        public int Chiet_khau { get; set; }
        public decimal Gia_chiet_khau { get; set; }
        public string Ghi_chu { get; set; }
        public System.DateTime Thoi_gian { get; set; }

        public virtual CuaHangVatTu CuaHangVatTu { get; set; }
        public virtual DanhMucVatTu DanhMucVatTu { get; set; }
    }
}
